### PR TITLE
Fix ibrowse version to 4.0.0

### PR DESCRIPTION
**Pull request by otoyo**
Fixes myfreeweb/httpotion#124

It seems ibrowse 4.0.1 has the problem.
So I fix ibrowse version to 4.0.0 in `mix.exs`.

This will remove after bugfix.

### CODE REVIEW

**Comment by myfreeweb** [comment]
Is the bug reported to ibrowse?

**Comment by otoyo** [comment]
No, not yet.

**Comment by iguberman** [comment]
I just had my `mix.lock` update from `ibrowse` 4.4.0 to 4.4.1 for some reason.   (My `httpotion` is 3.1.0) and suddenly I started having this hosts unreachable problem.    Changed `mix.lock` ibrowse version back to 4.4.0 and the problem went away.    It's been 4 months since this bug first opened, but looks like the problem is still around.  FYI.

**Comment by myfreeweb** [comment]
> for some reason

Yeah, sorry, I haven't released an httpotion version with this PR, the httpotion on hex.pm doesn't have the version locked. I'll do that now

**Comment by myfreeweb** [comment]
released 3.1.1

**Pull request merged**
