### PR TITLE
fix: HTTP headers are case insensitive

### PR DESCRIPTION
**Pull request by ckruse**
I tried to follow a redirect with `[ follow_redirects: true ]` and got a runtime error: the location header name was lower case. Since HTTP headers are case insensitive HTTPotion should downcase the header field before putting it to the dict

### CODE REVIEW

**Comment by ckruse** [comment]
Hu - I forgot to fix the tests, sorry. Pushed as well.

**Comment by myfreeweb** [comment]
Hmm, this is definitely the right thing to do, but this will break a lot of programs that use mixed case headers…

You should make a custom wrapper type around `Keyword` that downcases keys in its [`Access`](http://elixir-lang.org/docs/stable/elixir/Access.html) implementation.

**Comment by ckruse** [comment]
I thought about that, too, but `Access` is deprecated; one should use the `Dict` behavior instead. But the `Dict` behavior is deprecated as well...

**Comment by ckruse** [comment]
I'm not sure what to do. Of course backwards compatibility is important, but on the other hand I don't think that it makes much sense implementing deprecated protocols or behaviors.

But we would also fix a lot of existing code when implementing `Dict` or

**Comment by myfreeweb** [comment]
Where did you get that deprecation thing? The Access docs page I linked to does NOT have a deprecation warning!

**Comment by ckruse** [comment]
The compiler gives this warning:

    lib/httpotion.ex:279: warning: implementation of the Access protocol is deprecated. For customization of the dict[key] syntax, please implement the Dict behaviour instead

**Comment by myfreeweb** [comment]
Just use `Access`. And ask the Elixir developers what the hell are they doing with these deprecations :D

**Comment by ckruse** [comment]
Hehe ;-) Ok, I rewrote the patch; don't ask why I put the `access` function into the struct definition; there seems to be a problem with protocols in elixir 1.2.3, if I put them into the `defimpl` it can't find the function

**Comment by myfreeweb** [comment]
Thanks!

I wouldn't ask anything like that… I mean, I don't use Elixir for anything except maintaining this library :D

**Comment by ckruse** [comment]
That's sad! It's such a beautiful language :) Thanks for merging!

**Comment by ckruse** [comment]
As soon as this version has been released I can update my microformats2 library. When do you plan to release a new version? (Sorry for nagging)

**Comment by myfreeweb** [comment]
Microformats2? Wow, very nice! I wrote a [microformats2 parser in Haskell](https://github.com/myfreeweb/microformats2-parser)!

Yeah, this is a very important fix, I'll release now.

**Comment by ckruse** [comment]
Oh, YOU are the person who wrote the haskell mf2 parser? Nice to meet you! :) Thanks for your work! I already have been using it.

My MF2 parser is this one: <https://github.com/ckruse/microformats2-elixir>

**Comment by stevegraham** [comment]
This is a breaking change. Specifically process_response_headers/1 returning a struct instead of a list of headers.

**Comment by myfreeweb** [comment]
@stevegraham Two minor releases have been made already (with this change). If only you posted that comment before the releases…

I guess you were relying on the type being a list? Sorry. No one thought of that. Accessing elements didn't change, so tests didn't break, so I didn't consider this breaking.

Even overriding the function and returning a list still works, if you think of the public API as just `Access`.

Oh, also looks like the README shows it as a list in all examples and doesn't have a note about it not being a list…

**Pull request merged**
