### PR TITLE
Add query string support.

### PR DESCRIPTION
**Pull request by eidge**
This pull request adds the capability to specify query string parameters
in the options hash.

Ex.:

```elixir
iex> HTTPotion.get("www.example.com", query: %{page: 2}) # Yields a request with "www.example.com?page=2" as the url
```

### CODE REVIEW

**Comment by eidge** [comment]
Tests pass on my machine, did I broke something or is it a false positive?

**Comment by myfreeweb** [comment]
Maybe it's just intermittent errors with httpbin.

Why did you move base into a separate file?? o_0

**Comment by eidge** [comment]
It's just seemed weird to have two modules in the same file. But I can put it back there if you want :)

**Comment by eidge** [comment]
Is there a reason to have them both there?

**Comment by myfreeweb** [comment]
I don't like extra files and directories, there's no reason to split that file.

The thing is, you definitely shouldn't make changes like this in a pull request that adds a feature ;-)

If you could just remove that commit and force push your PR branch, that would be great.

**Comment by eidge** [comment]
Should be good now :)

**Comment by myfreeweb** [comment]
Thanks!

(GitHub doesn't say it's merged, because I've cherry-picked your commits, because you've rebased #71 onto something else and it would be duplicating those commits... I guess I could've removed them with an interactive rebase but fuck it, cherry-pick is easy)

**Comment by eidge** [comment]
Nice, thank you.

This is actually going to clean quite a bit of code in a project of mine :)

**Comment by myfreeweb** [comment]
Released 2.2.0 with this, redirects and finally, ibrowse from hex!

**Pull request closed without merging**
