### PR TITLE
Make other default options configurable

### PR DESCRIPTION
**Pull request by cwc**
From discussion in #75.

### CODE REVIEW

**Comment by myfreeweb** [comment]
You're not merging headers and ibrowse options! You should merge the default with e.g. `Dict.get(options, :headers, [])`. Otherwise passing in, say, `Authorization` only would erase the default `User-Agent`.

**Comment by cwc** [comment]
Ah, no problem. I assumed when you mentioned merging the options that you meant the user would have to do it or something.

**Comment by cwc** [comment]
Hrm, [`Dict` is deprecated](http://elixir-lang.org/docs/stable/elixir/Dict.html). Should I go ahead and switch this bit of logic to Map/Keyword (I guess Keyword in this case)?

**Comment by myfreeweb** [comment]
Yeah, definitely!

**Comment by cwc** [comment]
I think that logic is correct. I'd like to add a test or two using http://httpbin.org/headers to verify the payload with default and overridden values, but don't have the time at the moment.

**Comment by myfreeweb** [comment]
Thank you!

**Pull request merged**
