### PR TITLE
Specify default timeout in application config

### PR DESCRIPTION
**Pull request by cwc**
This allows users to override the default for an entire application.

### CODE REVIEW

**Comment by myfreeweb** [comment]
Great idea! Thanks!

**Comment by cwc** [comment]
Awesome! After using the library some more, I feel like this would be useful for other defaults as well (headers, ib_options, and follow_redirects). Would you like a pull request implementing app config defaults for some/all of those?

**Comment by myfreeweb** [comment]
Not sure about headers (there's an overridable `process_request_headers` function already) but yeah, adding this to follow_redirects seems fine.

ib_options? Hmm… I don't know when a default value for that makes sense.

**Comment by cwc** [comment]
For headers, I can imagine it being nice to set a default e.g. User-Agent without having to create a new module to override `process_request_headers`.

For ibrowse options, I think your README actually has a pretty good use case for it: setting a proxy.

**Comment by myfreeweb** [comment]
Fine. I guess that's reasonable. But you'd want to merge the defaults in, otherwise e.g. passing a different header only would erase the user-agent completely.

**Pull request merged**
