### PR TITLE
Add bang methods

### PR DESCRIPTION
**Pull request by bradleyd**
* Add bang functions for HTTP requests.

* Return `ErrorResponse` struct by default when there is an issue.

* Add catch all for `Response#success?`

I bumped version to `2.3.0` not sure how you would want to handle it.

### CODE REVIEW

**Comment by bradleyd** [comment]
now that I think about it..maybe the version should be bumped to `3.0.0` since technically they are breaking changes.

**Comment by myfreeweb** [comment]
About the version – I'll bump it to `3.0.0` later, please don't touch the version in pull requests.

Seems reasonable overall, except you're duplicating the `raise` code everywhere. Make a `request!` method that does the exception throwing and make other bang methods call it!

**Comment by bradleyd** [comment]
i will make changes and return the version back to what it was...sorry about that.

**Comment by bradleyd** [comment]
@myfreeweb better?  BTW, thanks for the feedback.

**Comment by myfreeweb** [comment]
Uh… almost. Except not really better. Please don't add any code duplication — [Don't Repeat Yourself](https://en.wikipedia.org/wiki/Don't_repeat_yourself)! (or others)

I meant something like this:
```elixir
      @doc """
      Like `request`, but raises  `HTTPotion.HTTPError` if failed.
      """
      @spec request!(atom, String.t, [{atom(), any()}]) :: %HTTPotion.Response{} | %HTTPotion.AsyncResponse{}
      def request!(method, url, options \\ []) do
        case request(method, url, options) do
          %HTTPotion.ErrorResponse{message: message} ->
            raise HTTPotion.HTTPError, message: message
          response -> response
        end
      end
```

Also, the `@spec` for the non-bang `request` should include `%HTTPotion.ErrorResponse{}` in the list of return types.

**Comment by bradleyd** [comment]
@myfreeweb 3rd time is a charm =]

**Comment by myfreeweb** [comment]
Looks good, thanks!

**Comment by bradleyd** [comment]
Thank you!

**Comment by chibicode** [comment]
@myfreeweb could you bump the version?

**Pull request merged**
